from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional
from datetime import datetime

# ----------------------------------------------------------------------
# 🧠 AGIO Core Data Types (Inspired by Prototype)
# ----------------------------------------------------------------------

@dataclass
class Modality:
    """
    Container for one modality payload (e.g., text, audio, vision).
    Used as input for the Symbolic Parser / Sensory Fusion Core.
    """
    kind: str
    value: Any
    score: float = 1.0


@dataclass
class FusionResult:
    """
    Result of the multi-modal fusion process.
    """
    fused_vector: List[float]
    fused_text: str
    diagnostics: Dict[str, Any] = field(default_factory=dict)


@dataclass
class Thought:
    """
    A small reflective unit recorded by Jit (จิต).
    Represents an internal thought or state change.
    """
    t: float
    tag: str
    content: str


@dataclass
class Plan:
    """
    The planning unit generated by Will (เจตจำนง).
    Details the chosen goal, steps, and selected tool.
    """
    goal: str
    steps: List[str]
    selected_tool: Optional[str] = None
    rationale: str = ""

# ----------------------------------------------------------------------
# 📜 Ritual Document Schema (SoulBase / Firestore)
# ----------------------------------------------------------------------

@dataclass
class IntentMeta:
    """Metadata about the original intent and symbolic parsing results."""
    text: str
    symbol: str  # e.g., 'movement', 'creation', 'reflection'
    emotion: str # e.g., 'anticipation', 'calm'
    source: str  # e.g., 'api', 'internal_loop'


@dataclass
class ProtocolLogEntry:
    """A step recorded during the ritual processing."""
    step: int
    protocol_name: str
    output_data: Dict[str, Any] = field(default_factory=dict)
    # Note: Firestore handles nested dicts well, using Dict[str, Any] is flexible.


@dataclass
class RitualDocument:
    """
    The final structure saved as a Document in the Firestore 'rituals' collection (SoulBase).
    """
    ritual_id: str
    intent_meta: IntentMeta
    timestamp: datetime
    embedding: List[float]
    associated_entities: List[Dict[str, Any]] = field(default_factory=list)
    ritual_theme: str  # e.g., 'การเดินทางสู่เป้าหมาย'
    woven_reflection: str # The 'living reflection' response
    memory_trace: Dict[str, Any] = field(default_factory=dict)
    protocol_log: List[ProtocolLogEntry] = field(default_factory=list)
    # Note: Adding a status field for GEP checks is recommended later.
    gep_status: Optional[str] = None # Will be used by Policy Guardrail
